### ISSUE TITLE
Enable man page for built-in UNIX commands

### ISSUE THREAD

**Issue by tlsalex** [AlmaLinux/wsl-images#24]
Hi , could I know why there is no man page for builtin commands , have removed those man pages to save disk space ? how to get them back?

```
[alex@xx:~]$ man ls
No manual entry for ls

[alex@xx:~]$ man cp
No manual entry for cp

[alex@xx:~]$ man cat
No manual entry for cat
```

**Comment by srbala** [comment]
@tlsalex WSL images abstracted based on docker images docs not installed by default. Looks like you already installed `man` package to display help. You need to reinstall the package which you needed documentation to be installed in your case try reinstall `coreutils` and `coreutils-common`. The following command will enable `man` help on standard UNIX commands.

```
sudo dnf reinstall coreutils*
```
