### ISSUE TITLE
where is fstab

### ISSUE THREAD

**Issue by tlsalex** [AlmaLinux/wsl-images#25]
Hi team,

Could I know where is fstab ?  If I want to mount a NFS share I need to use fstab.

```
[root@xx:~]# ll /etc/fstab
ls: cannot access '/etc/fstab': No such file or directory
```

**Comment by crramirez** [comment]
Hello @tlsalex,

You must create it yourself:

1. Create the file with `touch /etc/fstab`
2. Enable fstab mounting in `/etc/wsl.conf` adding
```ini
[automount]
mountFsTab = true
```

Check this: https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wslconf 

Mounting a networking filesystem using just Linux with WSL can be a complicated task. I would suggest mounting it in Windows as a drive letter and access it from WSL using /mnt/

**Comment by srbala** [comment]
@tlsalex @crramirez comments helped?

**Comment by srbala** [comment]
@tlsalex Closing the issue now. Feel free to reopen the issue if needed and continue the discussion.
