### ISSUE TITLE
Service control in AL9?

### ISSUE THREAD

**Issue by robpomeroy** [AlmaLinux/wsl-images#29]
This is more a question than an issue. Are there any plans to implement a `service` (init-style) wrapper script, as we see in e.g. the Ubuntu WSL distros? A colleague raised this with me, having attempted to install MySQL and run it as a service.

The [offical Microsoft WSL database guide](https://docs.microsoft.com/en-gb/windows/wsl/tutorials/wsl-database) advocates using `sudo service mysqld start`, which possibly would not work under *any* RHEL-derived distro? I experimented with installing the `initscripts` pacakge, but of course that simply calls SystemD, rather than offering a WSL-specific workaround.

This is slightly more than an academic question, since all the "solutions" on the internet suggest using `service start [foo]`. So possibly there will be more people trying the same. I accept however that the "better" approach is containers - which I use, but not all my colleagues are up to speed yet.

I don't know if I'm jumping the gun here incidentally, since #28 remains open - but AL9 is in the Microsoft Store, and I've been using it in dev (with delight 🙂).

Thanks!

**Comment by srbala** [comment]
> This is more a question than an issue. Are there any plans to implement a `service` (init-style) wrapper script, as we see in e.g. the Ubuntu WSL distros? 
I have seen some dirty hacks in the past. Might have to see how `ubuntu` does it. Interested. giving as a PR?

> I don't know if I'm jumping the gun here incidentally, since #28 remains open - but AL9 is in the Microsoft Store, and I've been using it in dev (with delight 🙂).

Thanks, updated!

**Comment by arinanto** [comment]
Maybe better to directly support systemd on WSL instead of wrapper script. Microsoft recently release a video on WSL systemd support in collaboration with Canonical.

[![WSL: Partnering with Canonical to support systemd](http://img.youtube.com/vi/Ja3qikzd-as/0.jpg)](https://youtu.be/Ja3qikzd-as "WSL: Partnering with Canonical to support systemd")

**Comment by robpomeroy** [comment]
@arinanto Ah, that's very interesting Rinaldi. I agree that would be the best answer to this issue; closing with thanks.
