### ISSUE TITLE
podman missing

### ISSUE THREAD

**Issue by csaket** [AlmaLinux/wsl-images#31]
Maybe a noob question.

Reading the announcement for AL9 I was expecting ~~python~~, podman etc to be present.
I just installed AL9 on wsl and do not have these.
Did not find any documentation around the same.
Is this a lite version or something? 

```
$ podman -v
bash: podman: command not found
```

**Comment by srbala** [comment]
@csaket do you need `python` or `podman`, both were two different packages.

You need to install podman package prior to use.

```
sudo dnf install -y podman
```

**Comment by csaket** [comment]
My confusion for python was around the announcements for AL 9 as it talks about it. I now know its there as python3.

The question on podman was due to some article mentioning it should be there. [How to install Podman support in Cockpit on AlmaLinux](https://www.techrepublic.com/article/install-podman-support-cockpit-almalinux-8/#:~:text=Podman%20should%20already%20be%20installed%20on%20AlmaLinux%20by%20default)

Thanks for clarifying.

**Comment by srbala** [comment]
> The question on podman was due to some article mentioning it should be there. [How to install Podman support in Cockpit on AlmaLinux](https://www.techrepublic.com/article/install-podman-support-cockpit-almalinux-8/#:~:text=Podman%20should%20already%20be%20installed%20on%20AlmaLinux%20by%20default)

It's not a correct statement that `podman` always installed. its depends on the what package group is installed on the server, for example "Container Management"

The Almalinux Windows WSL is minimal version of OS same as our docker/conainer image. But other packages or package groups can be installed and used using `dnf`
