### ISSUE TITLE
Can we have recent images and instructions for install without MS Store?

### ISSUE THREAD

**Issue by void-spark** [AlmaLinux/wsl-images#35]
A lot of enterprise setups allow you admin rights, but block the MS Store.
It would be nice to have images we can directly download and install, like for example Ubuntu also does :)

**Comment by wadebee** [comment]
I am in same situation. Unable to find this appx in a direct download package.

**Comment by crramirez** [comment]
You can use the side load version for that: https://github.com/AlmaLinux/wsl-images/releases/download/v9.0.4/AlmaLinux9WSL-amd64-SideLoad.zip

Having the appx needs a code signing certificate

**Comment by LKHN** [comment]
Hi all,
Good news! Direct links of appx files signed by MS Store - which means you can install it with one-click are available at wiki: https://wiki.almalinux.org/documentation/wsl.html

Please, let me know how the installation goes on your side.
