### ISSUE TITLE
0x800B010A This app package’s publisher certificate could not be verified...The root certificate and all immediate certificates of the signature in the app package must be verified

### ISSUE THREAD

**Issue by gamesharkmike** [AlmaLinux/wsl-images#40]
Downloaded AlmaLinux9-Appx_9.0.4.0_x64_arm64_bundle.appxupload , no default assocation for appxupload on this Windows 10 PC. Was able to open with 7-Zip file manager and extract DistroLauncher-Appx_9.0.4.0_x64_arm64.appxbundle file.

Get an error when opening DistroLauncher-Appx_9.0.4.0_x64_arm64.appxbundle file.

<img width="485" alt="0x800B010A_Screenshot 2024-01-06 120604" src="https://github.com/AlmaLinux/wsl-images/assets/6124851/d3570c14-9765-410d-b80a-e93d764f984a">

```
This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)
```

**Comment by LKHN** [comment]
See: https://github.com/AlmaLinux/wsl-images/issues/35#issuecomment-1938403856
